title: Chenyang Gu's Homepage
page-top-title: Chenyang Gu
top-section-bg-text: Embodied AI & Robotic Manipulation 
home-subtitle: Chenyang Gu&ensp;|&ensp;顾晨阳
copyright-text: '&copy; Chenyang Gu 2024-2025. All Rights Reserved.'
